steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/brennon-loveless/snippetbox-go:latest', '-f', 'deploy/docker/server/Dockerfile', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'gcr.io/brennon-loveless/snippetbox-go:latest', 'gcr.io/brennon-loveless/snippetbox-go:$SHORT_SHA' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/brennon-loveless/snippetbox-go:latest' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/brennon-loveless/snippetbox-go:$SHORT_SHA' ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['-n', 'javascript30', 'set', 'image', 'statefulset/snippetbox-go', 'go=gcr.io/brennon-loveless/snippetbox-go:$SHORT_SHA' ]
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['-n', 'javascript30', 'rollout', 'status', '-f', 'k8s/010-go-stateful-set.yaml' ]

options:
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1-a'
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=demon-k8s'

