apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: snippetbox-crt
  namespace: snippetbox
spec:
  secretName: snippetbox-crt
  dnsNames:
    - snippetbox.brennonloveless.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - snippetbox.brennonloveless.com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer

